title: Cosicas sobre Videojuegos
tagline: "Porque de algo hay que hablar, Â¿no?"
url: "https://throyd.github.io/gamestuff" # The base hostname & protocol for your site. Use it if you need absolute URL's

collections:
  games:
    name:
    key:
    steam:
    epic:
    gog:
    uplay:
    origin:
    nswitch:
    psx:
    ps2:
    ps3:
    ps4:
    ps5:
    psp:
    psvita:
    xone:
    xseriesx:
    stadia:
    cover:
    banner:
    link:    
    developer: 
    developer-link:
    publisher:
    publisher-link:
    launchdate: 
    output: true
    permalink: /juegos/:title/
  reviews:
    name:
    gamename:
    version:
    author:
    publisheddate:
    thumbs:
    output: true
    permalink: /criticas/:title/
  authors:
    name:
    aboutme:
    avatar:
    output: true
    permalink: /autores/:title/ 
  platform:
    name:
    hardware:
    icon:
    output: true
    permalink: /plataforma/:title/

defaults:
  -
    scope:
      path: ""
      type: "games"
    values:
      layout: "content_games"
  -
    scope:
      path: ""
      type: "reviews"
    values:
      layout: "content_reviews" 
      author: "Jhin"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "user_authors" 
  -
    scope:
      path: ""
      type: "platforms"
    values:
      layout: "content_platforms" 